# Generated by Django 4.1.5 on 2023-01-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tudu',
            new_name='Tudus',
        ),
    ]
