# Generated by Django 4.1.5 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0002_rename_tudu_tudus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tudus',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
