# Generated by Django 4.1.5 on 2023-01-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudu', '0003_alter_tudus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tudus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
